# Generated by Django 4.2.30 on 2026-07-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número do convite')),
                ('num_passes', models.PositiveSmallIntegerField(verbose_name='Quantidade de senhas')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(verbose_name='Posição da senha')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.invite')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('invite', 'slot')},
            },
        ),
    ]
