# Generated by Django 4.2.30 on 2026-07-06 22:36

from django.db import migrations

SAMPLE_INVITES = [
    ("01", 3),
    ("02", 2),
    ("03", 1),
    ("04", 4),
    ("05", 2),
]


def create_sample_invites(apps, schema_editor):
    Invite = apps.get_model("rsvp", "Invite")
    for number, num_passes in SAMPLE_INVITES:
        Invite.objects.get_or_create(number=number, defaults={"num_passes": num_passes})


def remove_sample_invites(apps, schema_editor):
    Invite = apps.get_model("rsvp", "Invite")
    numbers = [number for number, _ in SAMPLE_INVITES]
    Invite.objects.filter(number__in=numbers, confirmed=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_invites, remove_sample_invites),
    ]
