# Generated by Django 4.2.30 on 2026-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_seed_sample_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Anotação só para uso administrativo: a quem esse convite foi entregue. Não aparece no site.', max_length=150, verbose_name='Nome do convidado (uso interno)'),
        ),
    ]
