# Generated by Django 4.2.30 on 2026-08-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_invite_recipient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='recipient_name',
        ),
        migrations.CreateModel(
            name='ExpectedGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(verbose_name='Posição da senha')),
                ('name', models.CharField(max_length=150, verbose_name='Nome esperado (uso interno)')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_guests', to='rsvp.invite')),
            ],
            options={
                'verbose_name': 'Convidado esperado (uso interno)',
                'verbose_name_plural': 'Convidados esperados (uso interno)',
                'ordering': ['slot'],
                'unique_together': {('invite', 'slot')},
            },
        ),
    ]
