# Generated by Django 4.2.30 on 2026-09-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_remove_invite_recipient_name_expectedguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='reconfirmed_by_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Reconfirmado por WhatsApp'),
        ),
        migrations.AddField(
            model_name='invite',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Telefone de contato do convite, com DDD. Ex: (81) 91234-5678', max_length=20, verbose_name='Contato (WhatsApp)'),
        ),
    ]
