# Generated by Django 4.2.30 on 2026-09-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_invite_reconfirmed_by_whatsapp_invite_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Convite entregue'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], default='fisico', max_length=10, verbose_name='Tipo de convite'),
        ),
    ]
