# Generated by Django 4.2.30 on 2026-10-05 23:07

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_invite_delivered_invite_invite_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': [django.db.models.functions.text.Length('number'), 'number']},
        ),
    ]
