"""
Django settings for casamento project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de um .env local, se existir (sem depender de nenhuma
# biblioteca externa). Em produção, use variáveis de ambiente de verdade —
# elas têm prioridade e o .env é só uma conveniência para rodar localmente.
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith("#") or "=" not in _line:
            continue
        _key, _, _value = _line.partition("=")
        os.environ.setdefault(_key.strip(), _value.strip())

# SECURITY WARNING: don't run with debug turned on in production!
# Padrão seguro: False. Para ligar em dev, defina DJANGO_DEBUG=True no .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# Defina DJANGO_SECRET_KEY nas variáveis de ambiente do servidor. A chave
# abaixo só existe para não quebrar um `runserver` local sem .env configurado
# — nunca é usada se DEBUG=False.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "django-insecure-dev-only-nao-use-em-producao"

if not DEBUG and SECRET_KEY == "django-insecure-dev-only-nao-use-em-producao":
    raise RuntimeError(
        "DJANGO_SECRET_KEY precisa ser definido nas variáveis de ambiente quando DEBUG=False."
    )

# Sistema de baixo risco (confirmação de presença de casamento) — liberado para
# qualquer host. Troque pelo domínio definitivo quando ele estiver disponível,
# ex.: ['casamento.com', 'www.casamento.com'].
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rsvp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'casamento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'casamento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cada arquivo estático ganha um hash no nome (ex: painel.a3f9c1.css) sempre
# que o conteúdo muda, então o navegador nunca serve uma versão em cache
# desatualizada depois de um novo `collectstatic` — problema que já
# aconteceu aqui antes.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Login da página interna de convites (aberta a qualquer usuário autenticado,
# não só staff — diferente do /admin/, que exige is_staff).
LOGIN_URL = 'rsvp:login'
LOGIN_REDIRECT_URL = 'rsvp:lista_convites'
LOGOUT_REDIRECT_URL = 'rsvp:login'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Segurança em produção
# https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
# Ativado junto com DEBUG=False. Se o servidor não estiver atrás de HTTPS,
# apague estas 3 linhas.

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
